### ISSUE TITLE
make 3.0.0 release available ?

### ISSUE THREAD

**Issue by rudzboy** [kanersps/fivem-essentialmode#2]
If the answer is NO, well this is sad :disappointed_relieved: since handling updates is great wth Git

If the answer is YES

When ?
Could you mark the latest 2.0 version with a tag ?
Same for the first 3.0 stable version.

I know development team is complaining about receiving dumb questions, and I complain myself watching how forum threads are crowded with dumb conversations... The best way to avoid this and save time from support is to provide the most user-friendly (theorical :rofl: ) like upgrade and base tutorial guide.

I try to make the upgrade and rewrite my DB queries on custom scripts ASAP (the sooner the better).

Anyway, Thanks for your work.
Any enlightment on this subject would be great.

Good luck facing the dumb angry propaganda.

**Comment by kanersps** [comment]
https://kanersps.pw/files/essential_yeahprivatenow.zip
